import type { V2Copy, V2HotkeyCopy, V2PassCopy } from "./copy.ts";

/** English plural: 1 word, 2 words. */
export function pluralizeEn(count: number, one: string, many: string): string {
  return count === 1 ? one : many;
}

/** English v2 catalog. Typed against the Ukrainian one: a missing or extra key fails the type check. */
export const EN: V2Copy = {
  dateLocale: "en-US",
  stats: (words: number, paragraphs: number): string =>
    `${words} ${pluralizeEn(words, "word", "words")} · ${paragraphs} ${pluralizeEn(paragraphs, "paragraph", "paragraphs")}`,
  brand: "Orest Edit",
  untitledSource: "Manuscript",
  untitledChapter: "Untitled",
  saved: "Saved",
  saving: "Saving…",
  saveFailed: "Could not save the draft",
  undo: "Undo",
  redo: "Redo",
  history: "History",
  historyTitle: "Accepted changes",
  more: "More",
  moreTitle: "More actions",
  menuMore: {
    replace: "Find and replace",
    hotkeys: "Keyboard shortcuts",
    clear: "Clear document",
    recoveryHeld: (count: number): string => `Can be brought back: ${count} replaced ${pluralizeEn(count, "document", "documents")}`,
    restoreOne: (reason: "clear" | "open", time: string, excerpt: string): string =>
      `${reason === "clear" ? "Bring back the one cleared at" : "Bring back the one replaced at"} ${time}${excerpt ? ` — “${excerpt}”` : ""}`
  },
  historyPanel: {
    title: "Change history",
    empty: "No accepted changes yet.",
    before: "Before",
    after: "After",
    nothingBefore: "Block added.",
    nothingAfter: "Block removed.",
    back: "Back to the list",
    close: "Close",
    open: (label: string): string => `Compare: ${label}`,
    count: (count: number): string => `${count} ${pluralizeEn(count, "change", "changes")}`,
    blocks: (count: number): string => `${count} ${pluralizeEn(count, "block", "blocks")}`,
    image: "Image",
    divider: "Divider",
    table: "Table",
    kinds: {
      replace: "Text edit",
      heading: "Subheading",
      accent: "Emphasis",
      callout: "Callout",
      spell: "Spelling",
      visual: "Illustration",
      visualReplace: "Illustration replaced",
      visualRemove: "Illustration removed",
      caption: "Illustration caption",
      bulk: "Accepted together",
      globalReplace: "Find and replace"
    },
    bulkLabel: (name: string, count: number): string => `${name} · ${count}`,
    replaceLabel: (find: string, replacement: string): string => `“${find}” → “${replacement}”`
  },
  replace: {
    title: "Find and replace",
    find: "Find",
    with: "Replace with",
    hint: "The search is case-sensitive.",
    count: (count: number): string => `${count} ${pluralizeEn(count, "match", "matches")}`,
    none: "Nothing found.",
    typeQuery: "Type what to look for.",
    same: "The replacement is the same text.",
    action: "Replace all",
    done: (count: number): string => `Replaced: ${count}`,
    failed: "The text has changed. Nothing was replaced.",
    close: "Close"
  },
  hotkeys: {
    title: "Keyboard shortcuts",
    close: "Close",
    macNote: "On a Mac use ⌘ instead of Ctrl.",
    groups: [
      {
        title: "Text",
        items: [
          { keys: "Ctrl+B", text: "Bold" },
          { keys: "Ctrl+I", text: "Italic" },
          { keys: "Ctrl+Z", text: "Undo" },
          { keys: "Ctrl+Shift+Z / Ctrl+Y", text: "Redo" },
          { keys: "Shift+Enter", text: "New line in the same paragraph" },
          { keys: "Ctrl+H", text: "Find and replace" }
        ]
      },
      {
        title: "Selected fragment",
        items: [
          { keys: "Alt+F10", text: "Go to the actions for the selected text" },
          { keys: "← →", text: "Next or previous action" },
          { keys: "Esc", text: "Back to the text" }
        ]
      },
      {
        title: "Panel",
        items: [
          { keys: "F6", text: "Move between the text, the panel and the message" },
          { keys: "← →", text: "Neighbouring tab (while focus is on the tabs)" },
          { keys: "Enter", text: "On a card: show the edit" },
          { keys: "Ctrl+/", text: "This list" }
        ]
      },
      {
        title: "Quiet mode",
        items: [
          { keys: "Enter", text: "Accept the edit on screen, or prepare it" },
          { keys: "Backspace / Delete", text: "Reject" },
          { keys: "← →", text: "Previous or next suggestion" }
        ]
      },
      {
        title: "Illustration studio",
        items: [
          { keys: "Enter", text: "On an illustration card: open the studio" },
          { keys: "Tab", text: "Next control of the studio or of the message" },
          { keys: "Esc", text: "Close the studio" }
        ]
      }
    ] as Array<{ title: string; items: V2HotkeyCopy[] }>
  },
  confirm: {
    cancel: "Cancel",
    clearTitle: "Clear the document?",
    clearText: "The text, suggestions, reports and history will be removed.",
    recoveryKept: "You can bring the document back from the More menu until the page is reloaded.",
    recoveryDropsOldest: (time: string): string => `The oldest kept document (${time}) can no longer be brought back.`,
    recoveryNone: "The current draft cannot be brought back.",
    clearAction: "Clear",
    openTitle: "Replace the current text?",
    openText: "The new text replaces the current one together with its suggestions, reports and history.",
    openAction: "Replace",
    restartTitle: "Start over?",
    restartText: "The saved data is damaged. It will be deleted and an empty document will open.",
    restartAction: "Delete and start over",
    restart: "Start over",
    restartFailed: "Could not start over.",
    cleared: "The document was cleared.",
    restore: "Bring back",
    restored: "Document restored.",
    restoreFailed: "Could not bring back the previous document.",
    restoreWrongLocale: "This document was saved under another interface language."
  },
  a11y: {
    panel: "Editor's assistant",
    toast: "Message",
    live: {
      passDone: (name: string, count: number): string =>
        count > 0 ? `${name}: done, ${count} ${pluralizeEn(count, "suggestion", "suggestions")}.` : `${name}: done, no suggestions.`,
      passFailed: (name: string): string => `${name}: not finished, an error occurred.`,
      proposalReady: "The edit is prepared and shown in the text.",
      proposalFailed: "The edit was not prepared: an error occurred.",
      imageReady: "The image is ready.",
      imageFailed: "The image was not generated: an error occurred.",
      promptReady: "The illustration prompt is ready.",
      promptFailed: "The illustration prompt was not prepared: an error occurred."
    }
  },
  classic: "Classic version",
  classicTitle: "The previous version of the editor",
  open: "Open",
  openFile: "A .docx or .txt file",
  openClipboard: "Paste from the clipboard",
  export: "Export",
  exportDocx: "Word (.docx)",
  exportTxt: "Text (.txt)",
  dismiss: "Close",
  loading: "Opening the draft…",
  placeholder: "Start writing or open a file.",
  manuscriptLabel: "Manuscript text",
  imageMissing: "The image was not found in this browser",
  contentError: "The draft is damaged and could not be opened.",
  draftUnreadable: "The saved draft could not be read.",
  conflict: "The draft was changed in another tab. Saving is paused here.",
  reload: "Reload",
  savePaused: "Autosave stopped",
  draftNotOpened: "Draft not opened",
  draftReadFailed: "Could not read the draft from this browser.",
  imageInsertFailed: "Could not add the image.",
  toolbar: {
    label: "Formatting",
    blockType: "Paragraph style",
    paragraph: "Normal text",
    heading1: "Heading 1",
    heading2: "Heading 2",
    heading3: "Heading 3",
    bulletList: "Bulleted list",
    orderedList: "Numbered list",
    callout: "Callout",
    otherBlock: "Block",
    bold: "Bold",
    italic: "Italic",
    insertCallout: "Add a callout",
    insertImage: "Add an image"
  },
  tabs: {
    overview: "Overview",
    edits: "Edits",
    ask: "Request"
  },
  overview: {
    title: "Chapter overview",
    diagnostics: "Diagnostics",
    diagnosticsText: "What gets in the reader’s way",
    diagnosticsAction: "Read the chapter",
    mode: "Report depth",
    modeConcise: "Concise",
    modeExtended: "Extended",
    modeConciseHint: "Short report",
    modeExtendedHint: "Detailed report; takes longer",
    starting: "Starting…",
    diagnosticsRunning: "Reading the chapter…",
    diagnosticsFailed: "Diagnostics did not finish.",
    diagnosticsStopped: "Diagnostics was stopped.",
    diagnosticsEmpty: "The model returned an empty diagnostics report.",
    reportMeta: (mode: string, date: string) => (date ? `${mode} · ${date}` : mode),
    rerun: "Read again",
    stop: "Stop",
    shortcuts: "Run a check",
    shortcutTitle: (name: string) => `Run “${name}”`,
    busyRun: (name: string) => `Please wait: “${name}” is running.`,
    busyQueue: "Please wait: checks are running.",
    factCheck: "Fact check",
    factCheckText: "Questionable claims",
    factCheckAction: "Check",
    factRunning: "Checking the claims…",
    factFailed: "The fact check did not finish.",
    factStopped: "The fact check was stopped.",
    factCount: (count: number) => `${count} ${pluralizeEn(count, "finding", "findings")}`,
    factNoneTitle: "No doubtful claims found",
    factNoneText: (checked: number) => (checked > 0 ? `Claims checked: ${checked}.` : "The check only looks for obvious errors."),
    factRerun: "Check again",
    statusQuestionable: "doubtful",
    statusUnsupported: "not confirmed",
    sources: "Sources",
    noSource: "No reliable source",
    toEdit: "To the edit",
    toEditDecided: "Edit decided",
    toEditMissing: "This claim is no longer in the text.",
    askAuthor: "Ask the author",
    askAuthorAdded: "In the questions for the author",
    authorTitle: "Questions for the author",
    authorAdded: "Added to the questions for the author.",
    authorNoteLabel: "Note for the author",
    authorNotePlaceholder: "Note for the author (optional)",
    authorRemove: "Remove",
    copyAll: "Copy all",
    copied: "Copied.",
    copyFailed: "Could not copy.",
    copyText: {
      heading: (chapterTitle: string) => `Questions for the author — “${chapterTitle}”`,
      note: "Editor's comment",
      why: "Why the question came up",
      sources: "Sources",
      noSource: "No reliable source found"
    },
    runNames: { diagnostics: "Diagnostics", fact_check: "Fact check", request: "Own request" }
  },
  edits: {
    passes: "Checks",
    run: "Run",
    rerun: "Again",
    rerunTitle: "Run again",
    stop: "Stop",
    starting: "starting",
    reading: "reading",
    readingProgress: (done: number, total: number) => `reading · ${done} of ${total}`,
    done: "done",
    stopped: "stopped",
    failed: "error",
    openCountTitle: "Waiting for a decision",
    notLive: "Not connected yet",
    soon: "soon",
    runAll: "Run all",
    runAllTitle: "Run all checks one after another",
    stopAll: "Stop all",
    queued: "queued",
    queuedPaused: "queued · paused",
    resumeQueue: "Continue the queue",
    resumeQueueTitle: "Run the checks that were waiting",
    clearQueue: "Clear the queue",
    restore: "Bring back",
    ignored: "The word was left as it is.",
    reasonAccent: "The key phrase of the paragraph.",
    reasonMissing: "The model gave no reason for this change.",
    unqueue: "Remove",
    unqueueTitle: "Remove from the queue",
    checking: "checking",
    runFailed: "The check did not finish.",
    runWarnings: (count: number) => `Fragments the model did not process: ${count}.`,
    queue: "Suggestions",
    emptyTitle: "No suggestions yet",
    waitingTitle: "The model is reading the chapter…",
    noneFoundTitle: "No suggestions",
    allDecidedTitle: "Everything is decided",
    filterDoneTitle: "Everything is decided here",
    filterOnly: (name: string) => `Only “${name}”`,
    showAll: "show all",
    bulkAccept: (count: number) => `Accept all · ${count}`,
    bulkAcceptTitle: "Accept every change shown in the text",
    bulkAccepted: (count: number) => `Accepted: ${count}.`,
    bulkFailed: "The text has changed. Nothing was applied.",
    quiet: "Quiet mode",
    quietTitle: "One change at a time, by keyboard. Changes are prepared automatically.",
    quietPosition: (index: number, total: number) => `${index} of ${total}`,
    keyAccept: "accept",
    keyShow: "show",
    keyReject: "reject",
    keyMove: "next",
    previous: "Previous",
    next: "Next",
    whatHeading: (title: string) => `Subheading: “${title}”`,
    whatHeadingEmpty: "Subheading without a title",
    whatAccent: (phrase: string) => `Emphasise: “${phrase}”`,
    whatCallout: (kind: string, title: string) => `${kind}: “${title}”`,
    insert: "Insert",
    whatVisual: (intent: string, title: string) => `${intent}: “${title}”`,
    openStudio: "Open the studio",
    keyStudio: "studio",
    visualPreparing: "The model is preparing the illustration brief…",
    visualPromptFailed: "The illustration was not prepared.",
    visualGenerating: "Generating the image…",
    visualGenerationFailed: "The image was not generated.",
    visualInterrupted: "Generation was interrupted. Generate again.",
    visualReady: "The image is ready.",
    visualStale: "Settings changed — generate again.",
    visualGone: "The paragraph was deleted. This suggestion can only be rejected.",
    headingLevel: "Heading level",
    headingEmpty: "Type the subheading title in the text.",
    headingGone: "The paragraph was deleted. This suggestion can only be rejected.",
    accentStale: "The phrase is gone or already bold.",
    notDrawn: "The change is not shown in the text, so it cannot be accepted.",
    prepareCallout: "Prepare the callout",
    preparingCallout: "Preparing the callout…",
    calloutKind: "Callout type",
    calloutDepth: "Length",
    calloutEmpty: "The model returned a callout without text.",
    spellSuggestions: "Possible corrections",
    spellNoSuggestion: "No suggestions. Fix it by hand or leave it.",
    spellStale: "The word has changed. Check the spelling again.",
    ignore: "Leave as is",
    addToDictionary: "Add to the dictionary",
    dictionaryAdded: (word: string) => `“${word}” was added to the dictionary.`,
    dictionaryFailed: "Could not add the word to the dictionary.",
    dictionaryReadFailed: "Could not read the spelling dictionary.",
    spellEmpty: "The chapter has no text to check.",
    summaryOpen: (count: number): string => (count === 1 ? "edit waiting" : "waiting for a decision"),
    staleTag: "outdated",
    staleVisualsNote: (count: number): string => `Illustrations with no place in the text: ${count}.`,
    dismissStale: (count: number): string => `Remove · ${count}`,
    dismissStaleTitle: "Remove these illustrations from the suggestions",
    staleDismissed: (count: number): string => `Illustrations removed: ${count}.`,
    summaryDecided: (count: number) => `${count} decided`,
    whereParagraph: (label: string) => `para. ${label}`,
    whereHeading: "heading",
    whereBlock: "block",
    whereGone: "fragment changed",
    accept: "Accept",
    reject: "Reject",
    show: "Show the edit",
    preparing: "Preparing the edit…",
    retry: "Try again",
    prepareAgain: "Prepare again",
    recommendation: "What to do",
    changeReason: "What changed",
    stale: "The text has changed. Prepare the change again.",
    staleGone: "The fragment was deleted. This suggestion can only be rejected.",
    proposalFailed: "The edit was not prepared.",
    proposalUnsupported: "This kind of suggestion is not supported yet.",
    noOpRepeat: "The model returned almost the same text. Refine the request.",
    diffEmpty: "The model did not change the text. Refine the request or reject.",
    diffMismatch: "The text has changed, so the change cannot be shown. Regenerate it.",
    acceptNeedsDiff: "Show the change in the text first.",
    regenerateFailed: "Could not regenerate. The previous change is shown.",
    unexpected: "An unexpected error occurred.",
    refineLabel: "Refinement for the model",
    refinePlaceholder: "For example: keep the term but explain it",
    regenerate: "Regenerate",
    regenerateWithRefine: "Regenerate with the refinement",
    refinePending: "The refinement was not sent: regenerate or clear it.",
    applyFailed: "The text has changed. Prepare the change again.",
    accepted: "Change accepted.",
    rejected: "The suggestion was rejected.",
    emptyDocument: "The chapter has no text.",
    anotherRun: "Please wait: another check is running.",
    runElsewhere: "This check is running in another tab.",
    runOutdated: "The text has changed. Run the check again.",
    stopFailed: "The server did not confirm the stop:",
    writeBlocked: "The draft is not being saved, so AI actions are off.",
    sourceNames: { fact: "Facts", request: "Request" },
    passList: [
      { id: "structure", name: "Structure", text: "Subheadings where the topic changes" },
      { id: "clarity", name: "Clarity", text: "Simpler language without losing meaning" },
      { id: "interest", name: "Callouts", text: "Analogies and explanations for the reader" },
      { id: "formatting", name: "Lists", text: "Enumerations where a list reads better" },
      { id: "visual", name: "Illustrations", text: "Diagrams and pictures for difficult places" },
      { id: "accent", name: "Emphasis", text: "Key phrases in bold" },
      { id: "spell", name: "Spelling", text: "Spelling mistakes and typos" }
    ] as V2PassCopy[]
  },
  studio: {
    label: "Illustration studio",
    close: "Close",
    tag: "Illustrations",
    ghostKind: (intent: string) => `Visual · ${intent}`,
    edit: "Edit",
    intent: "Image type",
    intents: { infographic: "Infographic", illustration: "Illustration" },
    quality: "Speed",
    prompt: "Prompt",
    promptPlaceholder: "Describe what should be in the image.",
    promptPreparing: "Preparing the prompt…",
    promptFailed: "The prompt was not prepared.",
    promptRetry: "Try again",
    promptEmpty: "Write a prompt or",
    promptPrepare: "prepare one automatically",
    promptPrepareTitle: "The model writes a prompt from the paragraph",
    generateNeedsPrompt: "A prompt is needed.",
    promptMismatch: (intent: string, style: string) => `The prompt was written for “${intent} · ${style}”.`,
    promptRefresh: "Update the prompt",
    promptRefreshTitle: "The model rewrites the prompt; your edits to it are lost",
    promptCancel: "Cancel",
    style: "Style",
    caption: "Caption",
    captionPlaceholder: "Caption under the image (optional)",
    captionSave: "Save the caption",
    captionSaved: "Caption updated.",
    generate: "Generate",
    regenerate: "Regenerate",
    insert: "Insert into the text",
    insertNeedsImage: "Generate an image first.",
    insertNeedsFresh: "Settings changed — regenerate the image.",
    reject: "Reject",
    inText: "In the text",
    remove: "Remove from the text",
    removed: "Illustration removed.",
    replace: "Replace in the text",
    replaceSame: "This image is already in the text.",
    replaced: "Image replaced.",
    inserted: "Illustration inserted.",
    applyFailed: "There is no longer a place for the illustration in the text.",
    previewEmpty: "No image generated yet",
    previewStale: "Does not match the current settings",
    previewMissing: "The image was not found. Generate it again.",
    previewLoading: "Opening the image…",
    generatingImage: "Creating the image…",
    previewBroken: "The image could not be shown",
    previewBrokenHint: "Try again or regenerate.",
    previewRetry: "Try again",
    whyGenerating: "The image is still being created.",
    whyPreparing: "The prompt is still being prepared.",
    whyBroken: "The image did not open.",
    whyLoading: "The image is opening…",
    elapsed: (seconds: number) => `${seconds} s`,
    cancel: "Cancel",
    cancelled: "Generation cancelled.",
    generationFailed: "The image was not generated.",
    interrupted: "Generation was interrupted. Generate again.",
    manualLead: "This image was added by hand — only the caption can be changed.",
    figureGone: "This illustration is no longer in the text.",
    alt: (title: string) => `Illustration: ${title}`
  },
  api: {
    visualPromptInvalid: "The server returned a response that could not be read as an illustration brief.",
    visualPromptEmpty: "The model returned an empty response instead of an illustration brief.",
    imageInvalid: "The server returned a response that could not be read as an image generation result.",
    imageEmpty: "Generation ended without an image, and the server did not explain why.",
    imageTimeout: "The image model did not answer in time. Try generating again.",
    assetFailed: "The image was generated, but it could not be saved in this browser.",
    invalid: "The server returned a response that could not be read as the state of the check.",
    platformTimeout: "The check exceeded the server's time limit. Run the check again.",
    pollTimeout: "The server did not answer the status check. The run was stopped so that it does not hang.",
    wrongLocale: "The check was created for another application language. Run the check again.",
    resultInvalid: "The run ended without a valid response. Run the check again.",
    proposalInvalid: "The server returned a response that could not be read as an edit.",
    spellInvalid: "The server returned a response that could not be read as a spelling check result.",
    network: "Could not connect to the server.",
    localInvalid: "The server returned a response that could not be read as an action for the fragment.",
    patchInvalid: "The server returned a response that could not be read as an edit of the fragment.",
    patchNoOperations: "The model proposed no change for this fragment.",
    patchFallback: "The server returned a fallback draft instead of the model's answer. It is not shown."
  },
  ask: {
    title: "Own request",
    scope: "Whole chapter",
    scopeFragment: (where: string) => `Fragment · ${where}`,
    unscope: "Whole chapter",
    placeholder: "What should be done with the chapter?",
    placeholderFragment: "What should be done with this fragment?",
    send: "Send",
    empty: "Type a request.",
    examples: "For example",
    ideas: ["Cut the introduction in half", "Add a real-life example", "Explain the terms more simply"] as string[],
    quickTitle: "Quick actions for the fragment",
    quick: {
      simplify: "Simpler",
      shorten: "Shorter",
      list: "As a list",
      subsection: "Subheading",
      callout: "Callout",
      visual: "Illustration",
      spell: "Spelling"
    },
    own: "Own request",
    composerLabel: "Actions for the selected fragment",
    fragmentRunning: (label: string) => `${label}: waiting for the answer…`,
    cancel: "Cancel",
    starting: "Starting…",
    planning: "Planning the edits…",
    generating: (done: number, total: number) => `Preparing the edits · ${done} of ${total}`,
    generatingPlain: "Preparing the edits…",
    retrying: "Repeating the action…",
    stop: "Stop",
    failed: "The request was not carried out.",
    stopped: "The request was stopped.",
    history: "Earlier requests",
    outcomeRunning: "running…",
    outcomeDone: (count: number) =>
      count === 0 ? "The model proposed no edits" : `${count} ${pluralizeEn(count, "edit", "edits")}`,
    outcomeHoles: (count: number) => `not carried out: ${count}`,
    outcomeStopped: "stopped",
    outcomeQuestion: "needs clarification",
    outcomeInterrupted: "interrupted",
    showQueue: "Show the changes",
    holesTitle: "Not carried out",
    holeRetry: "Repeat",
    retryUnavailable: "This action can no longer be retried.",
    clarifyTitle: "What should be done with the fragment?",
    clarifyChoices: {
      patch: "Rewrite the text",
      callout: "Prepare a callout",
      visual: "Prepare an illustration",
      spellcheck: "Check the spelling"
    },
    clarifyDismiss: "Cancel the request",
    fragmentBusy: "Please wait: the previous request is still running.",
    scopeGone: "The fragment has changed. Select the text again.",
    scopeNotText: "Select text only — no images, tables or callouts.",
    spellPartial: (count: number) => `Spelling was only partly checked (skipped: ${count}).`,
    outcomeWarnings: (count: number) => `not checked completely: ${count}`,
    patchUnusable: "The model returned a change for a different fragment.",
    reasonFallback: "The model did not explain this edit.",
    manualReason: (label: string) => `Your request: ${label.toLocaleLowerCase("en")}.`,
    customTitle: "Own request"
  },
  settings: "Settings"
};
