import type { V2Copy, V2HotkeyCopy, V2PassCopy } from "./copy.ts";

/** English plural: 1 word, 2 words. */
export function pluralizeEn(count: number, one: string, many: string): string {
  return count === 1 ? one : many;
}

/** English v2 catalog. Typed against the Ukrainian one: a missing or extra key fails the type check. */
export const EN: V2Copy = {
  dateLocale: "en-US",
  stats: (words: number, paragraphs: number): string =>
    `${words} ${pluralizeEn(words, "word", "words")} · ${paragraphs} ${pluralizeEn(paragraphs, "paragraph", "paragraphs")}`,
  brand: "Orest Edit",
  untitledSource: "Manuscript",
  untitledChapter: "Untitled",
  saved: "Saved",
  saving: "Saving…",
  saveFailed: "Could not save the draft",
  undo: "Undo",
  redo: "Redo",
  history: "History",
  historyTitle: "Accepted changes of this draft",
  more: "More",
  moreTitle: "Find and replace, keyboard shortcuts, clear",
  menuMore: {
    replace: "Find and replace",
    hotkeys: "Keyboard shortcuts",
    clear: "Clear document",
    recoveryHeld: (count: number): string => `Can be brought back: ${count} replaced ${pluralizeEn(count, "document", "documents")}`,
    restoreOne: (reason: "clear" | "open", time: string, excerpt: string): string =>
      `${reason === "clear" ? "Bring back the one cleared at" : "Bring back the one replaced at"} ${time}${excerpt ? ` — “${excerpt}”` : ""}`
  },
  historyPanel: {
    title: "Change history",
    lead: "Accepted suggestions and replacements in this draft. What you typed by hand is not listed here.",
    empty: "Accepted changes will appear here: what changed, where and when.",
    before: "Before",
    after: "After",
    nothingBefore: "This block did not exist — it was added.",
    nothingAfter: "The block was removed from the text.",
    back: "Back to the list",
    close: "Close",
    open: (label: string): string => `Compare: ${label}`,
    count: (count: number): string => `${count} ${pluralizeEn(count, "change", "changes")}`,
    capNote: (limit: number): string => `Only the latest changes are kept, ${limit} at most.`,
    blocks: (count: number): string => `${count} ${pluralizeEn(count, "block", "blocks")}`,
    image: "Image",
    divider: "Divider",
    table: "Table",
    kinds: {
      replace: "Text edit",
      heading: "Subheading",
      accent: "Emphasis",
      callout: "Callout",
      spell: "Spelling",
      visual: "Illustration",
      visualReplace: "Illustration replaced",
      visualRemove: "Illustration removed",
      caption: "Illustration caption",
      bulk: "Accepted together",
      globalReplace: "Find and replace"
    },
    bulkLabel: (name: string, count: number): string => `${name} · ${count}`,
    replaceLabel: (find: string, replacement: string): string => `“${find}” → “${replacement}”`
  },
  replace: {
    title: "Find and replace",
    find: "Find",
    with: "Replace with",
    hint: "Looks for an exact, case-sensitive match in paragraphs, headings, lists and callouts.",
    count: (count: number): string => `${count} ${pluralizeEn(count, "match", "matches")}`,
    none: "Nothing found.",
    typeQuery: "Type what to look for.",
    same: "The replacement is the same as the search text: there is nothing to change.",
    action: "Replace all",
    done: (count: number): string => `Replaced ${count} ${pluralizeEn(count, "match", "matches")}. One Undo takes all of them back.`,
    failed: "Could not replace: the text has changed. Nothing was changed.",
    close: "Close"
  },
  hotkeys: {
    title: "Keyboard shortcuts",
    close: "Close",
    macNote: "On a Mac use ⌘ instead of Ctrl.",
    groups: [
      {
        title: "Text",
        items: [
          { keys: "Ctrl+B", text: "Bold" },
          { keys: "Ctrl+I", text: "Italic" },
          { keys: "Ctrl+Z", text: "Undo" },
          { keys: "Ctrl+Shift+Z / Ctrl+Y", text: "Redo" },
          { keys: "Shift+Enter", text: "New line in the same paragraph" },
          { keys: "Ctrl+H", text: "Find and replace" }
        ]
      },
      {
        title: "Selected fragment",
        items: [
          { keys: "Alt+F10", text: "Go to the actions for the selected text" },
          { keys: "← →", text: "Next or previous action" },
          { keys: "Esc", text: "Back to the text" }
        ]
      },
      {
        title: "Panel and queue",
        items: [
          { keys: "F6", text: "Move between the text, the panel and the message" },
          { keys: "← →", text: "Neighbouring tab (while focus is on the tabs)" },
          { keys: "Enter", text: "On a card: show the edit" },
          { keys: "Ctrl+/", text: "This list" }
        ]
      },
      {
        title: "Quiet mode",
        items: [
          { keys: "Enter", text: "Accept the edit on screen, or prepare it" },
          { keys: "Backspace / Delete", text: "Reject" },
          { keys: "← →", text: "Previous or next suggestion" }
        ]
      },
      {
        title: "Illustration studio",
        items: [
          { keys: "Enter", text: "On an illustration card: open the studio" },
          { keys: "Tab", text: "Next control of the studio or of the message" },
          { keys: "Esc", text: "Close the studio" }
        ]
      }
    ] as Array<{ title: string; items: V2HotkeyCopy[] }>
  },
  confirm: {
    cancel: "Cancel",
    clearTitle: "Clear the document?",
    clearText:
      "This removes the chapter text, every suggestion in the queue, the diagnostics and fact-check reports, the questions for the author, earlier requests and the change history. Passes that are running will be stopped.",
    recoveryKept:
      "The current document, with its suggestions and history, can be brought back from the “More” menu — until the page is reloaded or the interface language is changed. The last three replaced documents are kept.",
    recoveryDropsOldest: (time: string): string => `Three are kept already: the oldest of them (${time}) cannot be brought back after this.`,
    recoveryNone: "The draft that is stored now could not be opened, so it cannot be kept for recovery: after the replacement it is gone.",
    clearAction: "Clear",
    openTitle: "Replace the current text?",
    openText:
      "The new text takes the place of the current one. Suggestions in the queue, the diagnostics and fact-check reports, the questions for the author, earlier requests and the change history will be removed. Passes that are running will be stopped.",
    openAction: "Replace",
    restartTitle: "Start over?",
    restartText:
      "The saved draft of the new version cannot be read. Starting over deletes the damaged data from this browser and opens an empty document. It cannot be brought back afterwards. The draft of the classic version is not affected.",
    restartAction: "Delete and start over",
    restart: "Start over",
    restartFailed: "Could not start over.",
    cleared: "The document was cleared.",
    restore: "Bring back",
    restored: "The previous document is back, with its suggestions and history.",
    restoreFailed: "Could not bring back the previous document.",
    restoreWrongLocale:
      "This document belongs to the draft of another interface language, so it was not brought back here. The draft of this language was not changed."
  },
  a11y: {
    panel: "Editor's assistant",
    toast: "Message",
    live: {
      passDone: (name: string, count: number): string =>
        count > 0 ? `${name}: done, ${count} ${pluralizeEn(count, "suggestion", "suggestions")}.` : `${name}: done, no suggestions.`,
      passFailed: (name: string): string => `${name}: not finished, an error occurred.`,
      proposalReady: "The edit is prepared and shown in the text.",
      proposalFailed: "The edit was not prepared: an error occurred.",
      imageReady: "The image is ready.",
      imageFailed: "The image was not generated: an error occurred.",
      promptReady: "The illustration prompt is ready.",
      promptFailed: "The illustration prompt was not prepared: an error occurred."
    }
  },
  classic: "Classic version",
  classicTitle: "Open the previous version of the editor",
  open: "Open",
  openFile: "A .docx or .txt file",
  openClipboard: "Paste from the clipboard",
  export: "Export",
  exportDocx: "Word (.docx)",
  exportTxt: "Text (.txt)",
  dismiss: "Close",
  loading: "Opening the draft…",
  placeholder: "Start writing or open a file.",
  manuscriptLabel: "Manuscript text",
  imageMissing: "The image was not found in this browser",
  contentError: "Could not open the draft: its structure is damaged. The saved text was not changed.",
  draftUnreadable:
    "The saved draft of the new version could not be read: the data in this browser is damaged or has an unknown format. It was not changed or replaced.",
  conflict:
    "The draft was changed in another tab. Autosave is stopped here so those changes are not overwritten; edits made in this tab after that are not saved.",
  reload: "Reload",
  savePaused: "Autosave stopped",
  draftNotOpened: "Draft not opened",
  draftReadFailed: "Could not read the draft from this browser.",
  imageInsertFailed: "Could not add the image.",
  toolbar: {
    label: "Formatting",
    blockType: "Paragraph style",
    paragraph: "Normal text",
    heading1: "Heading 1",
    heading2: "Heading 2",
    heading3: "Heading 3",
    bulletList: "Bulleted list",
    orderedList: "Numbered list",
    callout: "Callout",
    otherBlock: "Block",
    bold: "Bold",
    italic: "Italic",
    insertCallout: "Add a callout",
    insertImage: "Add an image"
  },
  tabs: {
    overview: "Overview",
    edits: "Edits",
    ask: "Request"
  },
  overview: {
    title: "Chapter overview",
    lead: "The AI reads the chapter and changes nothing in it.",
    diagnostics: "Diagnostics",
    diagnosticsText: "What gets in the reader's way: language, structure, gaps.",
    diagnosticsAction: "Read the chapter",
    mode: "Report depth",
    modeConcise: "Concise",
    modeExtended: "Extended",
    modeConciseHint: "A short report: the main diagnosis and the most important observations.",
    modeExtendedHint: "A detailed report with a map of the chapter. Takes longer on a long text.",
    starting: "Starting…",
    diagnosticsRunning: "Reading the chapter…",
    diagnosticsRunningHint: "On a long chapter this can take a few minutes. You can reload the page — the reading goes on.",
    diagnosticsFailed: "Diagnostics did not finish.",
    diagnosticsStopped: "Diagnostics was stopped.",
    diagnosticsEmpty: "The model returned an empty diagnostics report.",
    reportMeta: (mode: string, date: string) => (date ? `${mode} · ${date}` : mode),
    rerun: "Read again",
    rerunTitle: "Run diagnostics again. This report stays until the new one is ready.",
    stop: "Stop",
    shortcuts: "What next",
    shortcutsHint: "Run a pass — it gets this report as context.",
    shortcutTitle: (name: string) => `Run the “${name}” pass and go to the edits`,
    busyRun: (name: string) => `“${name}” is running now. The server handles one run at a time — wait for it to finish or stop it.`,
    busyQueue: "A queue of passes is running now. The server handles one run at a time — wait for it to finish or stop the queue.",
    factCheck: "Fact check",
    factCheckText: "Looks for doubtful claims. A finding can become an edit or a question for the author.",
    factCheckAction: "Check",
    factRunning: "Checking the claims…",
    factRunningHint: "The model looks for sources, so the check can take a few minutes.",
    factFailed: "The fact check did not finish.",
    factStopped: "The fact check was stopped.",
    factCount: (count: number) => `${count} ${pluralizeEn(count, "finding", "findings")}`,
    factNoneTitle: "No doubtful claims found",
    factNoneText: (checked: number) =>
      checked > 0
        ? `The model looked at ${checked} ${pluralizeEn(checked, "claim", "claims")} and flagged none.`
        : "The model flagged no claims. This is not a guarantee: the check looks only for obvious red flags.",
    factRerun: "Check again",
    factRerunTitle: "Run the check again. These findings stay until the new result is ready.",
    statusQuestionable: "doubtful",
    statusUnsupported: "not confirmed",
    sources: "Sources",
    noSource: "No reliable source",
    toEdit: "To the edit",
    toEditDecided: "Edit decided",
    toEditMissing: "This claim could not be found in the text, so there is no edit for it.",
    askAuthor: "Ask the author",
    askAuthorAdded: "In the questions for the author",
    authorTitle: "Questions for the author",
    authorLead: "Questions only the author can answer. The list is saved with the draft.",
    authorAdded: "Added to the questions for the author.",
    authorNoteLabel: "Note for the author",
    authorNotePlaceholder: "Note for the author (optional)",
    authorRemove: "Remove",
    copyAll: "Copy all",
    copied: "The questions for the author were copied to the clipboard.",
    copyFailed: "Could not copy to the clipboard.",
    copyText: {
      heading: (chapterTitle: string) => `Questions for the author — “${chapterTitle}”`,
      note: "Editor's comment",
      why: "Why the question came up",
      sources: "Sources",
      noSource: "No reliable source found"
    },
    runNames: { diagnostics: "Diagnostics", fact_check: "Fact check", request: "Own request" }
  },
  edits: {
    passes: "Passes",
    run: "Run",
    rerun: "Again",
    rerunTitle: "Run the pass again. Undecided suggestions of this pass will be replaced with new ones.",
    stop: "Stop",
    starting: "starting",
    reading: "reading",
    readingProgress: (done: number, total: number) => `reading · ${done} of ${total}`,
    done: "done",
    stopped: "stopped",
    failed: "error",
    openCountTitle: "Waiting for a decision",
    notLive: "This pass is not connected in the new version yet",
    soon: "soon",
    runAll: "Run all",
    runAllTitle: "Run every pass that has not run yet, one after another. The server runs one pass at a time.",
    stopAll: "Stop all",
    queued: "queued",
    queuedPaused: "queued · paused",
    resumeQueue: "Continue the queue",
    resumeQueueTitle: "Run, one after another, the passes that were waiting before the page was reloaded",
    clearQueue: "Clear the queue",
    queuePausedNote: "These passes were queued before the reload. They will not start by themselves: continue the queue or clear it.",
    restore: "Bring back",
    ignored: "The word was left as it is.",
    reasonAccent: "The key idea of the paragraph: emphasis helps the reader find it when skimming.",
    reasonMissing: "The model gave no reason for this suggestion.",
    unqueue: "Remove",
    unqueueTitle: "Take this pass out of the launch queue",
    checking: "checking",
    runFailed: "The pass did not finish.",
    runWarnings: (count: number) =>
      `The pass finished incompletely: the model did not process ${count} ${pluralizeEn(count, "fragment", "fragments")}.`,
    queue: "Queue",
    emptyTitle: "The queue is empty",
    emptyText: "Run a pass — suggestions appear here and in the text, each with a reason.",
    waitingTitle: "The model is reading the chapter",
    waitingText: "Suggestions will appear here as they are ready.",
    noneFoundTitle: "No suggestions",
    noneFoundText: "The model found nothing to change in this pass.",
    allDecidedTitle: "Everything is decided",
    allDecidedText: "You can run a pass again or export the chapter.",
    filterDoneTitle: "Everything is decided here",
    filterDoneText: "Choose another pass or show all edits.",
    filterOnly: (name: string) => `Only “${name}”`,
    showAll: "show all",
    bulkAccept: (count: number) => `Accept all · ${count}`,
    bulkAcceptTitle: "Accept every suggestion of this pass that is shown in the text right now. One Undo takes them back.",
    bulkAccepted: (count: number) => `Accepted ${count}. One Undo takes all of them back.`,
    bulkFailed: "Could not apply the suggestions: the text is different now. Nothing was changed.",
    quiet: "Quiet mode",
    quietTitle: "Show one edit at a time and work from the keyboard",
    quietNote:
      "Quiet mode prepares the edit for the current and the next suggestion on its own — each preparation is a model call. The rest are prepared only when you reach them.",
    quietPosition: (index: number, total: number) => `${index} of ${total}`,
    keyAccept: "accept",
    keyShow: "show",
    keyReject: "reject",
    keyMove: "next",
    previous: "Previous",
    next: "Next",
    whatHeading: (title: string) => `Subheading: “${title}”`,
    whatHeadingEmpty: "Subheading without a title",
    whatAccent: (phrase: string) => `Emphasise: “${phrase}”`,
    whatCallout: (kind: string, title: string) => `${kind}: “${title}”`,
    insert: "Insert",
    whatVisual: (intent: string, title: string) => `${intent}: “${title}”`,
    openStudio: "Open the studio",
    keyStudio: "studio",
    visualPreparing: "The model is preparing the illustration brief…",
    visualPromptFailed: "The illustration was not prepared.",
    visualGenerating: "Generating the image…",
    visualGenerationFailed: "The image was not generated.",
    visualInterrupted: "Generation was interrupted by a page reload. Nothing was sent again.",
    visualReady: "The image is ready. Open the studio to look at it and insert it into the text.",
    visualStale: "The settings changed after generation: the image has to be generated again.",
    visualGone: "The paragraph the illustration was to follow has been deleted. The suggestion can only be rejected.",
    headingLevel: "Heading level",
    headingEmpty: "The subheading has no title. Type one right in the text to insert it.",
    headingGone: "The paragraph the subheading was to precede has been deleted. The suggestion can only be rejected.",
    accentStale: "This phrase is no longer in the paragraph, or it is already bold. The suggestion can only be rejected.",
    notDrawn: "This suggestion is not shown in the text right now, so it cannot be accepted.",
    prepareCallout: "Prepare the callout",
    preparingCallout: "Preparing the callout…",
    calloutKind: "Callout type",
    calloutDepth: "Length",
    calloutEmpty: "The model returned a callout without text.",
    calloutOptionsHint: "Changing the type or the length prepares the callout again.",
    spellSuggestions: "Possible corrections",
    spellNoSuggestion: "The service offered no correction. Fix the word in the text or leave it as it is.",
    spellStale: "The word changed after the check. Run “Spelling” again to check it once more.",
    ignore: "Leave as is",
    addToDictionary: "Add to the dictionary",
    dictionaryAdded: (word: string) => `“${word}” was added to the dictionary: this word will not be flagged again.`,
    dictionaryFailed: "Could not add the word to the dictionary.",
    dictionaryReadFailed: "Could not read the spelling dictionary; words from it may be flagged as errors.",
    spellEmpty: "The chapter has no paragraphs or headings with text to check.",
    summaryOpen: (count: number): string => (count === 1 ? "edit waiting" : "waiting for a decision"),
    staleTag: "outdated",
    staleVisualsNote: (count: number): string =>
      `${count} ${pluralizeEn(count, "illustration has", "illustrations have")} lost the place in the text: the paragraph was deleted.`,
    dismissStale: (count: number): string => `Remove these illustrations · ${count}`,
    dismissStaleTitle:
      "Removes from the queue every illustration that has no place in the text any more, with its prompt and generated image. Right after that all of them can be brought back.",
    staleDismissed: (count: number): string => `Illustrations without a place in the text removed: ${count} — with their prompts and images.`,
    summaryDecided: (count: number) => `${count} decided`,
    whereParagraph: (label: string) => `para. ${label}`,
    whereHeading: "heading",
    whereBlock: "block",
    whereGone: "fragment changed",
    accept: "Accept",
    reject: "Reject",
    show: "Show the edit",
    preparing: "Preparing the edit…",
    retry: "Try again",
    prepareAgain: "Prepare again",
    recommendation: "What to do",
    changeReason: "What changed",
    stale: "The text of this fragment changed after the suggestion. Prepare the edit again to see it.",
    staleGone: "The fragment this suggestion belonged to was deleted or moved. It can only be rejected.",
    proposalFailed: "The edit was not prepared.",
    proposalUnsupported: "This type of suggestion is not supported in the new version yet.",
    noOpRepeat: "The model returned almost the same text again. Say exactly what to change and regenerate.",
    diffEmpty:
      "The model did not change the text of this fragment, so there is nothing to accept. Refine the task and regenerate, or reject the suggestion.",
    diffMismatch:
      "The edit could not be shown in the text: the fragment in the manuscript differs from the one it was prepared for. Only an edit that is visible can be accepted — regenerate it.",
    acceptNeedsDiff: "Only an edit shown in the text can be accepted.",
    regenerateFailed: "Could not regenerate; the previous edit is shown.",
    unexpected: "An unexpected error occurred.",
    refineLabel: "Refinement for the model",
    refinePlaceholder: "For example: keep the term but explain it",
    regenerate: "Regenerate",
    regenerateWithRefine: "Regenerate with the refinement",
    refinePending: "The refinement has not been sent yet: regenerate the edit or erase it.",
    applyFailed: "The edit could not be applied: the fragment in the text is different now. Prepare it again.",
    accepted: "The edit was accepted. Undo takes it back.",
    rejected: "The suggestion was rejected.",
    emptyDocument: "The chapter has no text to check.",
    anotherRun: "Another pass is still running. Wait for it to finish or stop it.",
    runElsewhere: "Another browser tab is already running this pass. The result will appear there.",
    runOutdated: "The check was started for a different text, so its result is not shown. Run the pass again.",
    stopFailed: "The pass was stopped here, but the server did not confirm the cancellation:",
    writeBlocked: "The draft cannot be saved right now, so AI actions are off.",
    sourceNames: { fact: "Facts", request: "Request" },
    passList: [
      { id: "structure", name: "Structure", text: "Subheadings where the topic changes" },
      { id: "clarity", name: "Clarity", text: "Simpler language without losing meaning" },
      { id: "interest", name: "Callouts", text: "Analogies and explanations for the reader" },
      { id: "formatting", name: "Lists", text: "Enumerations where a list reads better" },
      { id: "visual", name: "Illustrations", text: "Diagrams and pictures for difficult places" },
      { id: "accent", name: "Emphasis", text: "Key phrases in bold" },
      { id: "spell", name: "Spelling", text: "Spelling mistakes and typos" }
    ] as V2PassCopy[]
  },
  studio: {
    label: "Illustration studio",
    close: "Close",
    tag: "Illustrations",
    ghostKind: (intent: string) => `Visual · ${intent}`,
    edit: "Edit",
    intent: "Image type",
    intents: { infographic: "Infographic", illustration: "Illustration" },
    quality: "Speed",
    prompt: "Prompt",
    promptPlaceholder: "Describe what should be in the image.",
    promptPreparing: "Preparing the prompt…",
    promptFailed: "The prompt was not prepared.",
    promptRetry: "Try again",
    promptEmpty: "There is no prompt yet. Write it yourself or ask the model to compose it from the paragraph.",
    promptPrepare: "Prepare the prompt",
    promptPrepareTitle: "The model composes a prompt for the chosen type and style. This is a separate model call.",
    generateNeedsPrompt: "A prompt is needed first: write it or prepare it.",
    promptMismatch: (intent: string, style: string) =>
      `The prompt was written for “${intent} · ${style}”, but something else is chosen. Update the prompt or generate with this text.`,
    promptRefresh: "Update the prompt",
    promptRefreshTitle:
      "The model writes the prompt anew for the chosen type and style. This is a separate model call; your edits to the prompt will be replaced.",
    promptCancel: "Cancel",
    style: "Style",
    caption: "Caption",
    captionPlaceholder: "Caption under the image (optional)",
    captionSave: "Save the caption",
    captionSaved: "The caption was updated. Undo takes the change back.",
    generate: "Generate",
    regenerate: "Regenerate",
    insert: "Insert into the text",
    insertNeedsImage: "Generate an image first: only one you have seen can be inserted.",
    insertNeedsFresh: "The image does not match the prompt or the settings. Regenerate it to insert it.",
    reject: "Reject",
    inText: "In the text",
    remove: "Remove from the text",
    removed: "The illustration was removed from the text. Undo brings it back.",
    replace: "Replace in the text",
    replaceSame: "This image is already in the text.",
    replaced: "The image in the text was replaced. Undo takes the change back.",
    inserted: "The illustration was inserted. Undo removes it.",
    applyFailed: "Could not change the text: the place for the illustration is no longer there.",
    previewEmpty: "No image generated yet",
    previewEmptyHint: "Check the prompt and press “Generate”. Every generation is a call to the image model.",
    previewStale: "Does not match the prompt or the settings",
    staleNote: "The prompt or the settings changed after generation — regenerate.",
    previewMissing: "The image was not found in this browser's storage. Generate it again.",
    previewLoading: "Opening the image…",
    generatingImage: "The model is creating the image…",
    generatingHint: "If you cancel, the request has already been sent: it may be billed, but the result will not be shown.",
    previewBroken: "The image could not be shown",
    previewBrokenHint: "The file is in the browser's storage, but the browser could not open it. Try again or regenerate.",
    previewRetry: "Try again",
    whyGenerating: "Wait for the image to be generated, or cancel the generation.",
    whyPreparing: "Wait for the model to prepare the prompt, or cancel.",
    whyBroken: "The image could not be shown, so it cannot be inserted.",
    whyLoading: "The image is still opening.",
    elapsed: (seconds: number) => `${seconds} s`,
    cancel: "Cancel",
    cancelled: "Generation was cancelled. The request had already been sent to the model, so it may be billed; the result is not shown.",
    generationFailed: "The image was not generated.",
    interrupted: "Generation was interrupted by a page reload. Nothing was sent again — generate once more.",
    manualLead: "This image was added by hand, so it has no prompt. You can change the caption.",
    figureGone: "This illustration is no longer in the text.",
    alt: (title: string) => `Illustration: ${title}`
  },
  api: {
    visualPromptInvalid: "The server returned a response that could not be read as an illustration brief.",
    visualPromptEmpty: "The model returned an empty response instead of an illustration brief.",
    imageInvalid: "The server returned a response that could not be read as an image generation result.",
    imageEmpty: "Generation ended without an image, and the server did not explain why.",
    imageTimeout: "The image model did not answer in time. Try generating again.",
    assetFailed: "The image was generated, but it could not be saved in this browser.",
    invalid: "The server returned a response that could not be read as the state of the check.",
    platformTimeout: "The check exceeded the server's time limit. Run the pass again.",
    pollTimeout: "The server did not answer the status check. The run was stopped so that it does not hang.",
    wrongLocale: "The check was created for another application language. Run the pass again.",
    resultInvalid: "The run ended without a valid response. Run the pass again.",
    proposalInvalid: "The server returned a response that could not be read as an edit.",
    spellInvalid: "The server returned a response that could not be read as a spelling check result.",
    network: "Could not connect to the server.",
    localInvalid: "The server returned a response that could not be read as an action for the fragment.",
    patchInvalid: "The server returned a response that could not be read as an edit of the fragment.",
    patchNoOperations: "The model proposed no change for this fragment.",
    patchFallback: "The server returned a fallback draft instead of the model's answer. It is not shown."
  },
  ask: {
    title: "Own request",
    lead: "Ask in your own words. The answer arrives as edits in the queue, not as finished text.",
    scope: "Whole chapter",
    scopeHint: "To ask about a fragment, select it in the text.",
    scopeFragment: (where: string) => `Fragment · ${where}`,
    scopeWhole: "The request covers the whole paragraphs the selection touches.",
    unscope: "Work with the whole chapter",
    placeholder: "What should be done with the chapter?",
    placeholderFragment: "What should be done with this fragment?",
    send: "Send",
    empty: "Write what exactly to do: an empty request is not sent.",
    examples: "For example",
    ideas: ["Cut the introduction in half", "Add a real-life example", "Explain the terms more simply"] as string[],
    quickTitle: "Quick actions for the fragment",
    quick: {
      simplify: "Simpler",
      shorten: "Shorter",
      list: "As a list",
      subsection: "Subheading",
      callout: "Callout",
      visual: "Illustration",
      spell: "Spelling"
    },
    own: "Own request",
    composerLabel: "Actions for the selected fragment",
    fragmentRunning: (label: string) => `${label}: waiting for the answer…`,
    cancel: "Cancel",
    starting: "Starting…",
    planning: "Planning the edits…",
    generating: (done: number, total: number) => `Preparing the edits · ${done} of ${total}`,
    generatingPlain: "Preparing the edits…",
    retrying: "Repeating the action…",
    chapterRunningHint: "Edits will appear in the queue as they are ready. You can reload the page — the request goes on.",
    stop: "Stop",
    failed: "The request was not carried out.",
    stopped: "The request was stopped.",
    history: "Earlier requests",
    outcomeRunning: "running…",
    outcomeDone: (count: number) =>
      count === 0 ? "The model proposed no edits" : `${count} ${pluralizeEn(count, "edit", "edits")} in the queue`,
    outcomeHoles: (count: number) => `not carried out: ${count}`,
    outcomeStopped: "stopped",
    outcomeQuestion: "needs clarification",
    outcomeInterrupted: "interrupted by a page reload; not sent again",
    showQueue: "Show in the queue",
    holesTitle: "Not carried out",
    holesLead: "The model did not carry out these planned actions. Each can be repeated separately.",
    holeRetry: "Repeat",
    retryUnavailable: "This action can no longer be repeated: the request plan was not kept or the paragraph was deleted.",
    clarifyTitle: "Say what to do with the fragment",
    clarifyText: "The request does not make clear which action is needed. Choose one — nothing is sent without it.",
    clarifyChoices: {
      patch: "Rewrite the text",
      callout: "Prepare a callout",
      visual: "Prepare an illustration",
      spellcheck: "Check the spelling"
    },
    clarifyDismiss: "Cancel the request",
    fragmentBusy: "The previous request for a fragment is still running. Wait for the answer or cancel it.",
    scopeGone: "The fragment the request was about was changed or deleted. Select the text again.",
    scopeNotText:
      "The selection includes an image, a table, a callout or a divider. Only text can be rewritten: select paragraphs without them. The request was not sent.",
    spellPartial: (count: number) =>
      `The spelling was not checked completely: the service did not check ${count} ${pluralizeEn(count, "part", "parts")} of the fragment.`,
    outcomeWarnings: (count: number) => `not checked completely: ${count}`,
    patchUnusable: "The model returned an edit for paragraphs that are not in this fragment. It is not shown.",
    reasonFallback: "The model did not explain this edit.",
    manualReason: (label: string): string => `Your request for the selected fragment: ${label.toLocaleLowerCase("en")}.`,
    customTitle: "Own request"
  },
  footer: "The draft is saved in this browser",
  settings: "settings"
};
